### PR TITLE
Update react-hooks.md

### PR DESCRIPTION
**Pull request by enwee**
typos

### CODE REVIEW

**Comment by jsstrn** [comment]
Thanks @enwee for proposing the changes. Looking at the React documentation they use the term "function components" rather than "functional components"

From the React documentation: 

> This function is a valid React component because it accepts a single “props” (which stands for properties) object argument with data and returns a React element. We call such components “function components” because they are literally JavaScript functions.
– [Components and Props – React](https://reactjs.org/docs/components-and-props.html)

Could you make the changes such that the term "functional component" is corrected to "function component" instead? 

Thank you.

**Comment by jsstrn** [comment]
Also, it is a good idea to use better titles for your git commit messages. For example, you might say: "Amend functional to function components"

**Comment by enwee** [comment]
thanks for your guiding comments, i actually used the [edit this doc]
button on the html page itself and did not that its comments field was
actually a git commit message. Following yr comments i wanted to edit the
content of the change request but again could not find how to so i created
a new edit. prob not the best way.

**Comment by jsstrn** [comment]
Closing this as it has been resolved in #93

**Pull request closed without merging**
